Repository ynput/ayon-maya, pull requests merged in 2024-09, with the labels that each got.

#85 Look Assigner: Ignore invalid entity ids in `get_folders` query
  client/ayon_maya/tools/mayalookassigner/commands.py
Labels: bug

#68 Add Extract Animation to ayon settings
  client/ayon_maya/plugins/publish/extract_fbx_animation.py
  client/ayon_maya/plugins/publish/extract_pointcache.py
  client/ayon_maya/plugins/publish/validate_alembic_options_defaults.py
  client/ayon_maya/plugins/publish/validate_animation_content.py
  client/ayon_maya/plugins/publish/validate_animation_product_type_publish.py
  client/ayon_maya/plugins/publish/validate_animation_rig_content.py
  client/ayon_maya/plugins/publish/validate_skeleton_top_group_hierarchy.py
  server/settings/publishers.py
Labels: enhancement

#89 AY-6654 Look: Fix None values in collecting and applying attributes
  client/ayon_maya/api/lib.py
  client/ayon_maya/plugins/publish/collect_look.py
Labels: bug, sponsored

#95 Extract Review: Fix "displayLights" not adhering to project settings of used profile
  client/ayon_maya/api/lib.py
  client/ayon_maya/plugins/publish/collect_review.py
Labels: bug, sponsored

#98 Set instance frame range attribute defaults to current task entity attributes
  client/ayon_maya/api/lib.py
  client/ayon_maya/plugins/create/create_animation_pointcache.py
  client/ayon_maya/plugins/create/create_arnold_scene_source.py
  client/ayon_maya/plugins/create/create_camera.py
  client/ayon_maya/plugins/create/create_maya_usd.py
  client/ayon_maya/plugins/create/create_multiverse_usd.py
  client/ayon_maya/plugins/create/create_multiverse_usd_comp.py
  client/ayon_maya/plugins/create/create_multiverse_usd_over.py
  client/ayon_maya/plugins/create/create_ornatrix_cache.py
  client/ayon_maya/plugins/create/create_redshift_proxy.py
  client/ayon_maya/plugins/create/create_review.py
  client/ayon_maya/plugins/create/create_unreal_yeticache.py
  client/ayon_maya/plugins/create/create_vrayproxy.py
  client/ayon_maya/plugins/create/create_yeti_cache.py
  server/settings/creators.py
Labels: enhancement

#93 Load to Maya USD Proxy Shape using AYON Entity URI for AYON USD Resolver
  client/ayon_maya/api/plugin.py
  client/ayon_maya/plugins/load/load_maya_usd.py
  server/settings/loaders.py
Labels: type: enhancement

#107 Look: Collect component assignment nodes as shapes
  client/ayon_maya/plugins/publish/collect_look.py
Labels: type: bug

#94 Create Multi-shot layout: Add label only if not same as shot name.
  client/ayon_maya/plugins/create/create_multishot_layout.py
Labels: type: bug

#112 Validate clashing sibling names when `strip namespaces` is enabled
  client/ayon_maya/plugins/publish/validate_clashing_sibling_names.py
Labels: type: enhancement

#109 Validate invisibilities of excluded parents (when "include parent hierarchy" is off)
  client/ayon_maya/plugins/publish/validate_excluded_parents_visible.py
Labels: type: enhancement

#104 Extract Layout: Add repre_type as json element
  client/ayon_maya/plugins/create/create_layout.py
  client/ayon_maya/plugins/publish/collect_layout_options.py
  client/ayon_maya/plugins/publish/extract_layout.py
Labels: type: enhancement

#128 Validate clashing siblings: Fix support for runtime instances
  client/ayon_maya/plugins/publish/validate_clashing_sibling_names.py
Labels: type: bug
