Repository ynput/ayon-maya, pull requests merged in 2024-08, with the labels that each got.

#60 Implement Maya USD Proxy extractor for one of the layers in the proxy
  client/ayon_maya/plugins/create/create_maya_usd_layer.py
  client/ayon_maya/plugins/publish/extract_maya_usd_layer.py
Labels: enhancement

#20 Improve Look publish validation reports
  client/ayon_maya/plugins/publish/help/validate_node_ids.xml
  client/ayon_maya/plugins/publish/validate_look_contents.py
  client/ayon_maya/plugins/publish/validate_look_sets.py
Labels: enhancement

#19 Disallow empty `cbId` value to pass through
  client/ayon_maya/api/lib.py
  client/ayon_maya/plugins/publish/validate_node_ids.py
Labels: bug

#70 Validate unique names only within the instance not in full scene
  client/ayon_maya/plugins/publish/validate_unique_names.py
Labels: enhancement, sponsored

#71 Maya Scene exports do not default to including nodes that not children of members
  client/ayon_maya/plugins/publish/extract_maya_scene_raw.py
Labels: bug

#75 Improve applying render resolution and aspect ratio on render settings reset
  client/ayon_maya/api/lib_rendersettings.py
Labels: bug, enhancement, sponsored

#77 Fix settings for Maya USD Animation Extractor
  server/settings/publishers.py
Labels: bug

#69 feature: add option for including shaders on model export.
  client/ayon_maya/plugins/create/create_model.py
  client/ayon_maya/plugins/publish/extract_model.py
  client/ayon_maya/plugins/publish/extract_obj.py
  server/settings/creators.py
Labels: enhancement
