Repository ynput/ayon-maya, pull requests merged in 2024-12, with the labels that each got.

#189 Extract Layout: Flatten Layouts on publish as JSON
  client/ayon_maya/plugins/publish/extract_layout.py
Labels: type: enhancement

#176 Load: Containerize `project_name` on load to allow managing containers from different projects
  client/ayon_maya/api/pipeline.py
  client/ayon_maya/api/plugin.py
Labels: type: enhancement

#178 Avoid being able to undo a part of containerisation
  client/ayon_maya/api/pipeline.py
Labels: type: enhancement

#198 Correct transform matrix data when extract layout
  client/ayon_maya/plugins/publish/extract_layout.py
Labels: type: bug

#180 Fix thumbnail extension to png
  client/ayon_maya/plugins/publish/extract_thumbnail.py
Labels: type: bug

#199 Load Layout from the json exported from maya layout should have correct transform
  client/ayon_maya/plugins/load/load_layout.py
Labels: type: bug, sponsored

#204 Store the render file directory as `stagingDir`
  client/ayon_maya/plugins/publish/validate_render_image_rule.py
Labels: type: bug

#193 Implement Maya USD Export Chaser to Filter Properties
  client/ayon_maya/api/chasers/README.md
  client/ayon_maya/api/chasers/export_filter_properties.py
  client/ayon_maya/api/pipeline.py
  client/ayon_maya/plugins/publish/collect_maya_usd_export_filter_properties.py
  client/ayon_maya/plugins/publish/extract_maya_usd.py
  server/settings/publishers.py
Labels: type: enhancement, sponsored

#187 AY-7271 Skip `worldspace` flag if not supported by Maya USD version
  client/ayon_maya/plugins/publish/extract_maya_usd.py
Labels: type: bug, sponsored

#202 Remove `maya_` prefix from dirmap settings
  client/ayon_maya/api/plugin.py
  server/__init__.py
  server/settings/conversion.py
  server/settings/dirmap.py
  server/settings/main.py
Labels: type: bug
