Repository ynput/ayon-maya, pull requests merged in 2024-10, with the labels that each got.

#133 Update handle start and handle end on instances on task change
  client/ayon_maya/api/lib.py
Labels: type: enhancement

#129 Support underscore delimiter for yeti UDIM textures
  client/ayon_maya/api/lib.py
Labels: type: bug

#134 Allow update to switch between `ma` and `mb` representation
  client/ayon_maya/api/plugin.py
Labels: type: enhancement

#103 Remove deprecated color management settings
  client/ayon_maya/api/lib.py
  server/settings/imageio.py
Labels: bump minor

#141 Define app host name
  package.py
Labels: type: maintenance

#148 Fix including of containers with e.g. `layout` products
  client/ayon_maya/plugins/publish/extract_maya_scene_raw.py
Labels: type: bug, community

#152 Maya USD Proxy Loader: Do not use AYON Entity URI by default
  server/settings/loaders.py
Labels: type: bug

#151 Alembic Exports: Do not force a preroll starting at frame 0
  client/ayon_maya/api/alembic.py
  client/ayon_maya/plugins/publish/extract_pointcache.py
Labels: type: bug

#163 Create plugins: Apply settings correctly
  client/ayon_maya/api/plugin.py
  client/ayon_maya/plugins/create/create_render.py
  client/ayon_maya/plugins/create/create_vrayscene.py
Labels: type: bug

#166 Remove Python 2 ExitStack compatibility
  client/ayon_maya/api/exitstack.py
  client/ayon_maya/api/lib.py
Labels: type: maintenance

#161 Review: Don't add ftrack family
  client/ayon_maya/plugins/publish/collect_remove_marked.py
  client/ayon_maya/plugins/publish/collect_review.py
Labels: type: enhancement

#138 Enable/disable frame range attribute definitions based on "Export Animation Data" toggle
  client/ayon_maya/plugins/create/create_maya_usd.py
  package.py
Labels: type: enhancement, bump minor, community

#167 Support assigning maya look to multiple separate assets inside an Arnold `aiStandin` with alembic files.
  client/ayon_maya/tools/mayalookassigner/alembic.py
  client/ayon_maya/tools/mayalookassigner/app.py
  client/ayon_maya/tools/mayalookassigner/arnold_standin.py
  client/ayon_maya/tools/mayalookassigner/commands.py
Labels: type: enhancement, sponsored

#159 Use run_name __main__ with runpy for matchmove script
  client/ayon_maya/plugins/load/load_matchmove.py
Labels: type: bug, community
