Repository ynput/ayon-maya, pull requests merged in 2025-02, with the labels that each got.

#233 Create Workfile: Use cached entity queries from CreateContext
  client/ayon_maya/plugins/create/create_workfile.py
Labels: type: maintenance

#232 Ignore invalid audio filepaths with a warning instead of erroring during Extraction
  client/ayon_maya/plugins/publish/collect_review.py
Labels: type: enhancement, community

#237 Chore: Remove 'six' usage
  client/ayon_maya/api/lib.py
  client/ayon_maya/api/lib_renderproducts.py
  client/ayon_maya/api/lib_rendersettings.py
  client/ayon_maya/api/setdress.py
  client/ayon_maya/plugins/load/load_rendersetup.py
  client/ayon_maya/plugins/publish/extract_camera_mayaScene.py
  client/ayon_maya/plugins/publish/extract_look.py
  client/ayon_maya/plugins/publish/extract_maya_usd.py
  client/ayon_maya/plugins/publish/extract_multiverse_usd.py
  client/ayon_maya/plugins/publish/validate_instance_subset.py
  client/ayon_maya/plugins/publish/validate_mesh_overlapping_uvs.py
  client/ayon_maya/tools/mayalookassigner/alembic.py
Labels: type: enhancement

#242 Extract FBX: Export only once
  client/ayon_maya/plugins/publish/extract_fbx.py
Labels: type: bug

#240 Extract FBX Animation: Strip off only first level namespace
  client/ayon_maya/plugins/publish/extract_fbx_animation.py
Labels: type: bug, sponsored

#241 Allow importing MayaUSDReferenceLoader + do not show the "Import Reference" option on non-supported containers
  client/ayon_maya/plugins/inventory/import_reference.py
Labels: type: enhancement, community

#179 Skip invalid containers with a warning
  client/ayon_maya/api/pipeline.py
  client/ayon_maya/api/setdress.py
  client/ayon_maya/plugins/publish/extract_layout.py
Labels: type: enhancement, community

#243 Support deleting workfile instances
  client/ayon_maya/api/plugin.py
  client/ayon_maya/plugins/create/create_workfile.py
Labels: type: bug
