Repository ynput/ayon-maya, pull requests merged in 2025-06, with the labels that each got.

#290 Import Loader: Relabel `Clean Import` to `Strip existing AYON asset metadata`
  client/ayon_maya/plugins/load/actions.py
Labels: type: enhancement, community

#293 Only process `dagNode` type in `get_highest_in_hierarchy`
  client/ayon_maya/api/lib.py
Labels: type: enhancement, community

#295 Adding debug message for render product in Collect Render
  client/ayon_maya/plugins/publish/collect_render.py
Labels: type: bug, sponsored

#300 use `getStage` without passing `|world`
  client/ayon_maya/plugins/create/create_maya_usd_layer.py
  client/ayon_maya/plugins/publish/extract_maya_usd_layer.py
Labels: type: bug

#304 Settings: Refactor `conditionalEnum` -> `conditional_enum`
  server/settings/scriptsmenu.py
Labels: type: maintenance, community

#305 Add input connection and up-axis settings for Collect Fbx camera
  client/ayon_maya/plugins/publish/collect_fbx_camera.py
  server/settings/publishers.py
Labels: type: bug, sponsored

#302 Set scene units on new scene and add validation before scene save
  client/ayon_maya/api/lib.py
  client/ayon_maya/api/pipeline.py
  client/ayon_maya/plugins/publish/validate_maya_units.py
  server/settings/conversion.py
  server/settings/main.py
  server/settings/publishers.py
Labels: type: enhancement, sponsored
