Repository ynput/ayon-maya, pull requests merged in 2025-09, with the labels that each got.

#340 Add options of lock set on load when loading rig for animation publish
  client/ayon_maya/api/lib.py
  client/ayon_maya/api/plugin.py
  client/ayon_maya/plugins/load/load_reference.py
  server/settings/loaders.py
Labels: type: enhancement, sponsored

#347 Create: Use kwargs to call product name functions
  client/ayon_maya/api/plugin.py
Labels: type: enhancement

#348 Switch folders in scene inventory can update metadata with the asset across the libraries
  client/ayon_maya/api/lib.py
  client/ayon_maya/api/plugin.py
  client/ayon_maya/api/setdress.py
  client/ayon_maya/plugins/inventory/connect_ornatrix_rig.py
  client/ayon_maya/plugins/inventory/connect_xgen.py
  client/ayon_maya/plugins/inventory/connect_yeti_rig.py
  client/ayon_maya/plugins/load/load_arnold_standin.py
  client/ayon_maya/plugins/load/load_audio.py
  client/ayon_maya/plugins/load/load_gpucache.py
  client/ayon_maya/plugins/load/load_image.py
  client/ayon_maya/plugins/load/load_image_plane.py
  client/ayon_maya/plugins/load/load_look.py
  client/ayon_maya/plugins/load/load_multiverse_usd.py
  client/ayon_maya/plugins/load/load_multiverse_usd_over.py
  client/ayon_maya/plugins/load/load_redshift_proxy.py
  client/ayon_maya/plugins/load/load_rendersetup.py
  client/ayon_maya/plugins/load/load_vdb_to_arnold.py
  client/ayon_maya/plugins/load/load_vdb_to_redshift.py
  client/ayon_maya/plugins/load/load_vdb_to_vray.py
  client/ayon_maya/plugins/load/load_vrayproxy.py
  client/ayon_maya/plugins/load/load_vrayscene.py
  client/ayon_maya/plugins/load/load_xgen.py
  client/ayon_maya/plugins/load/load_yeti_cache.py
  client/ayon_maya/tools/mayalookassigner/lib.py
Labels: type: bug, sponsored

#346 Load: Added actions to lock and unlock container versions
  client/ayon_maya/plugins/inventory/lock_version.py
Labels: type: enhancement, sponsored
