Repository ynput/ayon-maya, pull requests merged in 2025-05, with the labels that each got.

#276 AY-7798 - Allow load image plane to load by file extension instead of representation name
  client/ayon_maya/plugins/load/load_image_plane.py
Labels: type: enhancement, sponsored

#278 Reference Maya USD: Avoid automatic up-axis and unit conversions
  client/ayon_maya/plugins/load/load_reference.py
Labels: type: enhancement, sponsored

#279 Supports to have imagePrefixes for mayahardware
  client/ayon_maya/api/lib_rendersettings.py
  server/settings/render_settings.py
Labels: type: bug, sponsored

#281 Validate Maya Units: Support optional toggle in settings
  client/ayon_maya/plugins/publish/validate_maya_units.py
Labels: type: bug, community
