Repository ynput/ayon-maya, pull requests merged in 2025-03, with the labels that each got.

#249 Extract Playblast: Task types settings show dropdown instead of text field
  server/settings/publish_playblast.py
Labels: type: bug, community

#247 Extract Playblast settings profiles: Allow to fallback to legacy capture settings if no matching profile
  client/ayon_maya/api/lib.py
Labels: type: bug

#250 Fix logged error with open file post initialization enabled if no workfile exists yet
  client/ayon_maya/hooks/pre_open_workfile_post_initialization.py
Labels: type: bug

#251 Fix writing redshift proxy filenames with number at end of filename (e.g. variant `env050`)
  client/ayon_maya/plugins/publish/extract_redshift_proxy.py
Labels: type: bug, sponsored

#252 AY-7454 Load Image Plane: Allow loading "jpeg" representation as image plane
  client/ayon_maya/plugins/load/load_image_plane.py
Labels: type: enhancement, sponsored

#257 Fix PreLaunchHooks if both explicit load plugins and open workfile post initialization is enabled.
  client/ayon_maya/hooks/pre_auto_load_plugins.py
  client/ayon_maya/hooks/pre_open_workfile_post_initialization.py
Labels: type: bug, sponsored

#259 Create Render: Use entity getters from `create_context`
  client/ayon_maya/api/plugin.py
Labels: type: enhancement, community

#260 Settings Extension Mapping: Change to `ma` and `mb` enum
  server/settings/main.py
Labels: type: enhancement, sponsored

#258 Maya USD: Support `mergeTransformAndShape` attribute for animation, pointcache and model product types
  client/ayon_maya/plugins/create/create_maya_usd.py
  client/ayon_maya/plugins/publish/extract_maya_usd.py
Labels: type: enhancement, sponsored

#264 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature

#263 Add ExtractSkeletonMesh to Publish settings.
  server/settings/publishers.py
Labels: type: enhancement, community
