Repository ynput/ayon-maya, pull requests merged in 2025-07, with the labels that each got.

#314 Connect Geometry: preserve cbId on deformed shapes
  client/ayon_maya/plugins/inventory/connect_geometry.py
Labels: type: bug, sponsored

#312 Workfile: Can be set as mandatory
  client/ayon_maya/plugins/create/create_workfile.py
  server/settings/creators.py
Labels: type: enhancement

#313 Support of Texture Reference Objects in Look Publish
  client/ayon_maya/api/lib.py
  client/ayon_maya/plugins/create/create_look.py
  client/ayon_maya/plugins/publish/collect_look.py
  client/ayon_maya/plugins/publish/extract_look.py
  server/settings/creators.py
Labels: sponsored, type: feature

#322 Creator Settings: Add settings for all creators
  client/ayon_maya/plugins/create/create_render.py
  server/settings/creators.py
Labels: type: enhancement, community

#315 Validate Default Shader Connections: Allow Maya 2026 openPBR_shader1 as connection to default shader
  client/ayon_maya/plugins/publish/validate_look_default_shaders_connections.py
Labels: type: enhancement, community

#296 Do not error on cbId attributes of different type than string
  client/ayon_maya/api/lib.py
Labels: type: bug, community
